name: Maintain Streamlit Web app

on:
  schedule:
    - cron: '0 */11 * * *'

  workflow_dispatch:

jobs:

  maintain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Push empty commit
      run: |
        git commit --allow-empty -m "Keepalive Commit $(date)"
        git pull --rebase
        git push
