
name: Maintain Streamlit Web app

on:
  schedule:
    - cron: '0 */11 * * *'  # Every 11 hours
  workflow_dispatch:

jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push empty commit
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git commit --allow-empty -m "Keepalive Commit $(date)"
          git pull --rebase origin main
          git push origin main

