
name: Maintain Streamlit Web app

on:
  schedule:
    - cron: '0 */11 * * *'
  workflow_dispatch:

jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push empty commit
        run: |
          git commit --allow-empty -m "Keepalive Commit $(date)"
          git pull --rebase origin main
          git push origin main
