[client]
showErrorDetails = "none"

[theme]

# The preset Streamlit theme that your custom theme inherits from.
#
# This can be one of the following: "light" or "dark".
base = "light"

# Primary accent color.
primaryColor = "#6b0000ff"

# Background color of the app.
backgroundColor = "#fff7e6ff"

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#f08649ff"

# Color used for almost all text.
textColor = "#6b0000ff"


# The font family for all text, except code blocks.
#
# This can be one of the following:
# - "sans-serif"
# - "serif"
# - "monospace"
font = "serif"
